name: ArcIamStoryPluginV2
main: com.github.miniyosshi.arciamstorypluginV2.ArcIamStoryPluginV2
version: 1.0
description: This is only for ArcIam server.
author: miniyosshi
api-version: 1.15

commands:  
  addarea:
    description: Set your location as the one corner or center of an area.
    usage: "/addarea [name of area] [square or round] [radius for roundArea]"
  
  modifyarea:
    description: Set your location as the one corner or center of an area that is already made.
    usage: "/modifyarea [name of area] [AorB for squareArea, radius for roundArea]"
  
  deletearea:
    descripstion: Delete an area.
    usage: "/deletearea [name of area]"
  
  showarea:
    descripstion: See set areas.
    
  setspot:
    description: aaa.
  
  showusers:
    description: See all users.
    
  money:
    description: aaa.
    
  createmerchant:
    description: aaa.
    
  goal:
    description: aaa.

    
