name: ArcIamStoryPluginV2
main: com.github.miniyosshi.arciamstorypluginV2.ArcIamStoryPluginV2
version: 1.0
description: This is only for ArcIam server.
author: miniyosshi
api-version: 1.15

commands:  
  ll:
    description: Primary command for LostLegacy.



permissions:
  arciamstorypluginv2.ll:
    description: Only for OP.
    default: op
    
    

    
